[package]
name = "scrollrack-cli"
version = "0.5.0"
edition = "2021"

[dependencies]
scrollrack-core = { path = "../scrollrack-core" }
clap = { version = "3.1.18", features = ["derive"] }
anyhow = "1.0"
tokio = "1.31.0"

[profile.release]
strip = true
