[package]
name = "scrollrack-backend"
version = "0.4.0"
edition = "2021"

[dependencies]
scrollrack-core = { path = "../scrollrack-core" }
anyhow = "1.0"
tokio = "1.31.0"
serde = { version = "1.0", features = ["derive"] }
rocket = { version = "0.5.1", features = ["json"] }
